// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMUCsTEGzOcsQdaBeiDGMHgYHU9Gl420Y',
    appId: '1:1063524992171:web:6bea3bf3800f505f6de3ee',
    messagingSenderId: '1063524992171',
    projectId: 'pln-monitoring-wisma-kelas',
    authDomain: 'pln-monitoring-wisma-kelas.firebaseapp.com',
    storageBucket: 'pln-monitoring-wisma-kelas.firebasestorage.app',
    measurementId: 'G-NGJTF2R1WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy4Og38mF5dz9QlD6Ah_EKbIa8-tiDf4k',
    appId: '1:1063524992171:android:28298480375a10206de3ee',
    messagingSenderId: '1063524992171',
    projectId: 'pln-monitoring-wisma-kelas',
    storageBucket: 'pln-monitoring-wisma-kelas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY5AdNIMlxA6mGkBCPM0mHp4AB-6GDQOw',
    appId: '1:1063524992171:ios:2a178dea284ce2996de3ee',
    messagingSenderId: '1063524992171',
    projectId: 'pln-monitoring-wisma-kelas',
    storageBucket: 'pln-monitoring-wisma-kelas.firebasestorage.app',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY5AdNIMlxA6mGkBCPM0mHp4AB-6GDQOw',
    appId: '1:1063524992171:ios:2a178dea284ce2996de3ee',
    messagingSenderId: '1063524992171',
    projectId: 'pln-monitoring-wisma-kelas',
    storageBucket: 'pln-monitoring-wisma-kelas.firebasestorage.app',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMUCsTEGzOcsQdaBeiDGMHgYHU9Gl420Y',
    appId: '1:1063524992171:web:4d25e59e193df9cd6de3ee',
    messagingSenderId: '1063524992171',
    projectId: 'pln-monitoring-wisma-kelas',
    authDomain: 'pln-monitoring-wisma-kelas.firebaseapp.com',
    storageBucket: 'pln-monitoring-wisma-kelas.firebasestorage.app',
    measurementId: 'G-12YXCFFSZM',
  );
}
